Drastically simplify rollback_clone
Mostly reverts bb946fddf61ae7ff39e04d82d1292ce425e6a3b3

diff --git a/boot/bin/rollback_clone b/boot/bin/rollback_clone
--- a/boot/bin/rollback_clone
+++ b/boot/bin/rollback_clone
@@ -2,17 +2,15 @@
 
 #
 # Expects two arguments:
-# SOURCE - source dataset or snapshot
+# SOURCE - source snapshot
 # DESTINATION - destination dataset
 #
-# Makes sure that DESTINATION has been rolled back to a pristine snapshot from
-# after it was cloned from SOURCE
+# Clone DESTINATION from SOURCE
 #
-# If SOURCE is a snapshot, this is relatively simple
-# If SOURCE is just a dataset, use the newest snapshot of it.
-# If no snapshot exists of the SOURCE dataset, create one to use.
+# If SOURCE failed to include a snapshot name, assume that the snapshot name
+# is supposed to be the same as the name of the last component of the dataset name
 #
-# This script can use _CERANA_CLONE_SOURCE and _CERANA_CLONE_DESTINATION environment variables
+# Will use _CERANA_CLONE_SOURCE and _CERANA_CLONE_DESTINATION environment variables
 # if present, but arguments trump environment variables
 
 set -o errexit
@@ -22,36 +20,16 @@ DESTINATION="${2:-${_CERANA_CLONE_DESTINATION}}"
 
 [[ -n "${SOURCE}" ]]
 [[ -n "${DESTINATION}" ]]
-SNAP=pristine
+
+if ! [[ "${SOURCE##*/}" =~ @ ]]; then
+    SOURCE="${SOURCE}@${SOURCE##*/}"
+fi
 
 export PATH=/run/current-system/sw/bin/
 
-zfs_exists() { zfs list -H -o name "${1}" &>/dev/null; }
-zfs_exists_or_snapshot() {
-    zfs_exists "${1}" \
-        || zfs snapshot "${1}"
-}
-zfs_origin() { zfs get -H -o value origin "${1}" 2>/dev/null; }
+zfs_exists() { zfs list -o name "${1}" &>/dev/null; }
+zfs_destroy() { zfs destroy -r "${DESTINATION}"; }
+zfs_clone() { zfs clone "${SOURCE}" "${DESTINATION}"; }
 
-IFS=@ read -r SOURCE_DATASET SOURCE_SNAPSHOT<<<"${SOURCE}"
-if [[ -z "${SOURCE_SNAPSHOT}" ]]; then
-    # If the snapshot name was an empty string then find or create a snapshot.
-    LATEST_SNAPSHOT=$(zfs list -o name -t snapshot -r "${SOURCE_DATASET}" 2>/dev/null | tail -n 1)
-    if [[ -z "${LATEST_SNAPSHOT}" ]]; then
-        # Found no snapshots. Create a snapshot named after the destination.
-        SOURCE="${SOURCE_DATASET}@${DESTINATION##*/}"
-    else
-        # Use the latest snapshot of the originally specified SOURCE.
-        SOURCE=${LATEST_SNAPSHOT}
-    fi
-fi
-
-zfs_exists_or_snapshot "${SOURCE}"
-
-if ! [[ "${SOURCE}" == $(zfs_origin "${DESTINATION}") ]]; then
-    zfs_exists "${DESTINATION}" \
-        && zfs destroy -r "${DESTINATION}"
-    zfs clone "${SOURCE}" "${DESTINATION}"
-fi
-zfs_exists_or_snapshot "${DESTINATION}@${SNAP}"
-zfs rollback -r "${DESTINATION}@${SNAP}"
+zfs_exists "${DESTINATION}" && zfs_destroy
+zfs_clone
